PKsite/project/infostats/urls.py
from django.urls import path

from . import views

app_name = 'infostats'

urlpatterns = [
    path('', views.index, name='index'),
    path('info_timeline/', views.info_timeline, name='timeline'),
    path('info_piechart/', views.info_piechart, name='piechart'),
    path('info_dynamics/', views.info_dynamics, name='dynamics'),
    path('stories/', views.stories, name='stories')
]

PKsite/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('infostats/', include('infostats.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls'))
]

PKsite/project/infostats/models.py
from django.db import models

# Create your models here.

PKsite/project/infostats/views.py
from django.shortcuts import render

from .dash_apps import timeline, piechart, dynamics


def index(request):
    return render(request, "index.html", {})


def info_timeline(request):
    return render(request, "info_timeline.html", {})


def info_piechart(request):
    return render(request, "info_piechart.html", {})


def info_dynamics(request):
    return render(request, "info_dynamics.html", {})


def stories(request):
    return render(request, "stories.html", {})

PKsite/project/infostats/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static "assets/favicon.ico" %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "css/styles.css" %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#">Cross the Border</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url "infostats:index" %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="https://github.com/kol-di/pogran-control-aggregator">Source</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Infographics</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "infostats:timeline" %}">Timeline</a></li>
                                <li><a class="dropdown-item" href="{% url "infostats:piechart" %}">Piechart</a></li>
                                <li><a class="dropdown-item" href="{% url "infostats:dynamics" %}">Dynamics</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url "infostats:stories" %}">Stories</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            {% block contents %}{% endblock %}
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static "js/scripts.js" %}"></script>
    </body>
</html>

PKsite/project/infostats/templates/index.html
{% extends "base.html" %}

{% block title%} Index {% endblock %}

{% block contents%}
    <h1 class="text-center mt-5">About</h1>
    <p class="lead">This resource is designed to monitor the chances to pass Russain borders. It collects data from the
    «Пограничный контроль» telegram channel. The info, provided there is quite unsystematic, so you might find some
    deteriorated location names. Hope that won't spoil your experience too much.</p>

    <p class="lead">From the «Infographics» dropdown you can access statistics of people, who have already tried to cross the borders.</p>

    <p class="lead">Good luck to all of you!</p>
{% endblock %}

PKsite/project/infostats/templates/info_dynamics.html
{% extends "base.html" %}

{% load plotly_dash %}

{% block title%}
    Info Dynamics
{% endblock %}

{% block contents%}
    <div class="text-center mt-5">
        <h1>Dynamics</h1>
    </div>
    {% plotly_app name="dynamics" ratio=1%}
{% endblock %}

PKsite/project/infostats/templates/info_piechart.html
{% extends "base.html" %}

{% load plotly_dash %}

{% block title%}
    Info Piechart
{% endblock %}

{% block contents%}
    <div class="text-center mt-5">
        <h1>Piechart</h1>
    </div>
    {% plotly_app name="piechart" ratio=1%}
{% endblock %}

PKsite/project/infostats/templates/info_timeline.html
{% extends "base.html" %}

{% load plotly_dash %}

{% block title%}
    Info Timeline
{% endblock %}

{% block contents%}
    <div class="text-center mt-5">
        <h1>Timeline</h1>
    </div>
    {% plotly_app name="timeline" ratio=1%}
{% endblock %}

PKsite/project/infostats/templates/stories.html
{% extends "base.html" %}

{% block title%} Stories {% endblock %}

{% block contents%}
    <h1 class="text-center mt-5">Stories</h1>
    <p class="lead">This page is yet under development.</p>
{% endblock %}